djangoProject6/urls.py
from django.contrib import admin
from django.urls import path
from Farmer import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('farm', views.farm),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),

]

Farmer/models.py
from django.db import models

# Create your models here.
from django.db import models
class Farmermodel(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    class Meta:
        db_table = "Farmer1"

Farmer/forms.py
from django import forms
from Farmer.models import Farmermodel
class FarmersForm(forms.ModelForm):
    class Meta:
        model = Farmermodel
        fields = "__all__"

Farmer/views.py
from django.shortcuts import render

# Create your views here.

# Create your views here.
from django.shortcuts import render, redirect
from Farmer.forms import FarmersForm
from Farmer.models import Farmermodel
# Create your views here.
def farm(request):
    if request.method == "POST":
        form = FarmersForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = FarmersForm()
    return render(request,'index.html',{'form':form})
def show(request):
    farms = Farmermodel.objects.all()
    return render(request,"show.html",{'farms':farms})
def edit(request, id):
    Farmer1 = Farmermodel.objects.get(id=id)
    return render(request,'edit.html', {'Farmer1':Farmer1})
def update(request, id):
    Farmer1= Farmermodel.objects.get(id=id)
    form = FarmersForm(request.POST, instance = Farmer1)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'Farmer1': Farmer1})
def destroy(request, id):
    Farmer1 = Farmermodel.objects.get(id=id)
    Farmer1.delete()
    return redirect("/show")

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>



</head>
<body>
<form method="POST" class="post-form" action="/update/{{Farmer1.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Farmer Id:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Farmer Name:</label>
    <div class="col-sm-4">
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ Farmer1.ename }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ Farmer.eemail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Farmer Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>


</head>
<body>
<form method="POST" class="post-form" action="/farm">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Farmer Id:</label>
    <div class="col-sm-4">
      {{ form.eid }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Farmer  Name:</label>
    <div class="col-sm-4">
      {{ form.ename }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Farmer Email:</label>
    <div class="col-sm-4">
      {{ form.eemail }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Farmer Contact:</label>
    <div class="col-sm-4">
      {{ form.econtact }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Farmer Records</title>


</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Farmer ID</th>
        <th>Farmer Name</th>
        <th>Farmer Email</th>
        <th>Farmer Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for Farmer1 in farms %}
    <tr>
        <td>{{ Farmer1.eid }}</td>
        <td>{{ Farmer1.ename }}</td>
        <td>{{ Farmer1.eemail }}</td>
        <td>{{ Farmer1.econtact }}</td>
        <td>
            <a href="/edit/{{ Farmer1.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ Farmer1.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/farm" class="btn btn-primary">Add New Record</a></center>

</body>
</html>